// import logo from './logo.svg';
import styles from '../styles/Checkout.module.css'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import { useForm } from "react-hook-form";
import { createClient } from '@supabase/supabase-js'
import { Router } from 'next/router';


function CheckoutPage() {
    const productNameVar = "Basil"
    const priceVar = "4.99"

    const router = useRouter();
    const supabaseUrl = 'https://fvgexbvyzbrwwvywxfpq.supabase.co'
    const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_KEY
    console.log(supabaseKey)
    

    const { register, handleSubmit } = useForm();
    const onSubmit = async (formData) => {
        const supabaseClient = createClient(supabaseUrl, supabaseKey)
        console.log(supabaseClient);


        const { data, error } = await supabaseClient
        .from('Product Test')
        .insert([
            {
                product: formData.product, 
                price: formData.price,
                quantity: formData.quantity,
                firstName: formData.firstName,
                lastName: formData.lastName,
                email: formData.email,
                address: formData.address,
                city: formData.city,
                state: formData.state,
                country: formData.country,
                discountCode: formData.discountCode
            },
        ])

        router.push(`/out-of-stock`)

    }

  return (
    <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous" />
            <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"></link>

        </Head>
        <main className={styles.main}>
            <form className="needs-validation" onSubmit={ handleSubmit(onSubmit) }>
                <div className="row">    
                    <div className="col-md-7">
                        <h4 className="mb-3">Billing address</h4>
                        
                            <div className="row">
                                <div className="col-md-6 mb-3 ">
                                
                                    <label htmlFor="firstName">First name</label>
                                    <input {...register("firstName", { required: true, maxLength: 20 })} className="form-control"/>

                                </div>
                                <div className="col-md-6 mb-3">
                                    <label htmlFor="lastName">Last name</label>
                                    <input {...register("lastName", { required: true, maxLength: 20 })} className="form-control" />
                                    
                                </div>
                            </div>

                            <div className="mb-3">
                                <label htmlFor="email">Email</label>
                                <input 
                                    {...register("email", { required: true, maxLength: 20, // pattern: 
                                        // {
                                        //     value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                                        //     message: "invalid email address"
                                        // } 
                                    })} 
                                    className="form-control"
                                    placeholder="you@example.com"
                                />
                                
                            </div>

                            <div className="mb-3">
                                <label htmlFor="address">Address</label>
                                <input className="form-control" id="address" placeholder="1234 Main St"  {...register("address", { required: true, maxLength: 20 })}/>
                                
                            </div>

                            <div className="mb-3">
                                <label htmlFor="address2">Address 2 <span className="text-muted">(Optional)</span></label>
                                <input type="text" className="form-control" placeholder="Apartment or suite" />
                            </div>

                            <div className="row">
                                <div className="col-md-4 mb-3">
                                    <label htmlFor="state">City</label>
                                    <input type="text" className="form-control" id="city" placeholder="" required="" {...register("city", { required: true, maxLength: 20 })}/>
                                </div>
                                <div className="col-md-4 mb-3">
                                    <label htmlFor="state">State</label>
                                    <input type="text" className="form-control" id="state" {...register("state", { required: true, maxLength: 20 })} />
                                </div>
                                <div className="col-md-4 mb-3">
                                    <label htmlFor="country">Country</label>
                                    <input type="text" className="form-control" id="country"  {...register("country", { required: true, maxLength: 20 })} />

                                </div>
                            </div>
                    </div>
                    <div className="col-md-5">
                        <div className="card">
                            <div className="card-body">
                                <img  src="../public/assets/images/basil.jpeg" className="d-flex justify-content-center"/>
                                <h4 className="card-title">{ productNameVar }</h4>
                                <h6>{ priceVar }</h6>
                                <p className="card-text">Product Description</p>
                                <select className="custom-select d-block w-100" id="country" {...register("quantity")}>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select> 
                                <label htmlFor="state">Enter your Discount Code</label>
                                <input type="text" className="form-control" {...register("discountCode")} />

                            </div>
                        </div>
                    </div>
                
                    <input className="btn btn-primary btn-lg btn-block" type="submit" value="Continue to checkout"/>
                
                </div>
            </form>
        </main>    
    </div>
  );
}

export default CheckoutPage; 