import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous" />
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"></link>

      </Head>

      <main className={styles.main}>
      <section className="header-main border-bottom">

      <header className="d-flex justify-content-center py-3">
        <ul className="nav nav-pills">
          <li className="nav-item"><a href="#" className="nav-link" aria-current="page">Company Name</a></li>
        </ul>
      </header>
      </section> 
      <section className="section-content padding-y bg">
        <div className="container">

        <article className="card">
            <div className="card-body">
                    <div className="row">
                        <aside className="col-md-6">
                                <article className="gallery-wrap">
                                    <div className="card img-big-wrap">
                                        <img src="http://s3-media1.ak.yelpcdn.com/bphoto/sMONYSiLUQEvooJ5hZh0Sw/l.jpg" className="img-fluid" alt="" width="400" height="300" />
                                    </div> 
                                    <div className="thumbs-wrap">
                                        <img src="assets/images/basil.jpeg" className="img-fluid" alt="" width="100" height="75" /> 
                                        <img src="assets/images/basil.jpeg" className="img-fluid" alt="" width="100" height="75" /> 
                                        <img src="assets/images/basil.jpeg" className="img-fluid" alt="" width="100" height="75" />
                                    </div>
                                </article>
                        </aside>
                        <main className="col-md-6">
                            <article>
                                <h3 className="title">Great product name goes here</h3>
                                <div>
                                  {/* Not working out of the box */}
                                    <ul className="rating-stars">
                                        <li className={styles.noBullet}>
                                            <i className="fa fa-star"></i><i className="fa fa-star"></i>
                                            <i className="fa fa-star"></i><i className="fa fa-star"></i>
                                            <i className="fa fa-star-half"></i>
                                            <p><small>4.6 out of 5 stars based on 91 ratings</small></p>
                                        </li>
                                    </ul>
                                  </div> 
        
                                <hr />
                    
                                <div className="mb-3">
                                    <h6>Short description</h6>
                                    <ul className="list-dots mb-0">
                                        <li className={styles.noBullet}>Made in Russia</li>
                                        <li className={styles.noBullet}>Wolf leather </li>
                                        <li className={styles.noBullet}>Rubber material bottom</li>
                                        <li className={styles.noBullet}>Dark blue color</li>
                                    </ul>
                                </div>
                                {/* Quantity Selection here */}
                                <div>

                                </div>
                                {/* <div className="form-group">
                                    <label className="text-muted">Available sizes</label>
                                    <div>
                                        <label className="js-check btn btn-check active mr-1">
                                            <input type="radio" name="option_size" value="option1" checked="" />
                                            <span>Small</span>
                                        </label>
                                        <label className="js-check btn btn-check mr-1">
                                            <input type="radio" name="option_size" value="option1" />
                                            <span>Medium</span>
                                        </label>
                                        <label className="js-check btn btn-check mr-1">
                                            <input type="radio" name="option_size" value="option1" />
                                            <span>Large</span>
                                        </label>
                                        <label className="js-check btn btn-check disabled">
                                            <input type="radio" name="option_size" disabled="" value="option1" />
                                            <span>Babies</span>
                                        </label>  
                                    </div>            
                                </div> */}
        
                                <div className="mb-3">
                                    <var className="price h4">$230.00</var> <br />
                                    <span className="monthly">$32.00 / monthly <a href="#" className="btn-link">installment </a></span>
                                </div> 
        
                                <div className="mb-4">
                                    <Link href="/checkout">
                                        <button className="btn btn-primary mr-1">Get yours</button>
                                    </Link>
                                </div>
                                
                            </article> 
                        </main>
                    </div> 
            </div> 
        </article>
        <article className="card mt-5">
            <div className="card-body">
                <div className="row">
                    <aside className="col-md-6">
                        <h5>Parameters</h5>
                        <dl className="row">
                              <dt className="col-sm-3">Display</dt>
                              <dd className="col-sm-9">13.3-inch LED-backlit display with IPS</dd>
        
                              <dt className="col-sm-3">Processor</dt>
                              <dd className="col-sm-9">2.3GHz dual-core Intel Core i5</dd>
        
                              <dt className="col-sm-3">Camera</dt>
                              <dd className="col-sm-9">720p FaceTime HD camera</dd>
        
                              <dt className="col-sm-3">Memory</dt>
                              <dd className="col-sm-9">8 GB RAM or 16 GB RAM</dd>
                              
                              <dt className="col-sm-3">Graphics</dt>
                              <dd className="col-sm-9">Intel Iris Plus Graphics 640</dd>
                        </dl>
                    </aside>
                    <aside className="col-md-6">
                        <h5>Features</h5>
                        <ul className="list-check">
                            <li >Best performance of battery</li>
                            <li >5 years warranty for this product</li>
                            <li >Amazing features and high quality</li>
                            <li >Best performance of battery</li>
                            <li >Best performance of battery</li>
                            <li >5 years warranty for this product</li>
                        </ul>
                    </aside>
                </div> 
                <hr />
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div> 
        </article>
        </div>
        

      </section>
    </main>

    <footer className="section-footer border-top padding-y">
      <div className="container">
          <p className="float-md-right"> 
              &copy; Copyright 2021 All rights reserved
          </p>
          <p>
              <a href="#">Terms and conditions</a>
          </p>
      </div>
    </footer>


    </div>
  )
}
