import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import { useForm } from "react-hook-form";
import { createClient } from '@supabase/supabase-js'
import { Router } from 'next/router';
import { useRouter } from 'next/router'


export default function Home() {


    const router = useRouter();
    const supabaseUrl = 'https://fvgexbvyzbrwwvywxfpq.supabase.co'
    const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_KEY
    

    const { register, handleSubmit } = useForm();

    const onSubmit = async (formData) => {
        const supabaseClient = createClient(supabaseUrl, supabaseKey)
        console.log(supabaseClient);


        const { data, error } = await supabaseClient
        .from('Product Test')
        .insert([
            {
                email: formData.email,
            },
        ])

        router.push(`/out-of-stock`)

    }
    return (
        <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous" />
            <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"></link>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        </Head>

        <main className={styles.main}>
        <section className="header-main border-bottom">

        <header className="d-flex justify-content-center py-3">
            <ul className="nav nav-pills">
                <li className="nav-item">
                    <Link href="#">
                        <span style={{fontSize:'80px;'}}>&#127850;</span>
                        {/* <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="" /> */}
                    </Link>
                </li>
            </ul>
        </header>
        </section> 
        <section className="section-content padding-y bg">
            <div className="container">

            <article className="card">
                <div className="card-body">
                        <div className="row">
                            <main className="col-md-6">
                                <article>
                                    <h1 className="title">Crack Cookies to your Door... Fast</h1>
                                    <div>
                                    {/* Not working out of the box */}
                                        <ul className="rating-stars">
                                            <li className={styles.noBullet}>
                                                <i className="fa fa-star"></i><i className="fa fa-star"></i>
                                                <i className="fa fa-star"></i><i className="fa fa-star"></i>
                                                <i className="fa fa-star-half"></i>
                                                <p><small>4.6 out of 5 stars based on 91 ratings</small></p>
                                            </li>
                                        </ul>
                                    </div> 
            
                                    <hr />
                        
                                    <div className="mb-3">
                                        <h6>Cookies so good you&apos;ll slap your grandma... and might end up on the street</h6>
                                        <ul className="list-dots mb-0">
                                            {/* <li className={styles.noBullet}>You before a Cookie &#128544;</li>
                                            <li className={styles.noBullet}>You after a Cookie &#128522;&#128525;</li>
                                            <li className={styles.noBullet}>Rubber material bottom</li>
                                            <li className={styles.noBullet}>Dark blue color</li> */}
                                            <li className={styles.noBullet}>Chocolate Chip (The kind you dreamt about as a kid)</li>
                                            <li className={styles.noBullet}>Oatmeal Raisin (For those of us with taste)</li>
                                            <li className={styles.noBullet}>Snicker Doodle (Who knows what this is... it just tastes great)</li>
                                            <li className={styles.noBullet}>Variety (For when you're feel indecisive)</li>
                                        </ul>
                                    </div>
                                    {/* Quantity Selection here */}
                                    <div>

                                    </div>        
                                    <div className="mb-3">
                                        <var className="price h4">&euro;20 / 12 Cookies</var> <br />
                                        {/* <span className="monthly">$32.00 / monthly <a href="#" className="btn-link">installment </a></span> */}
                                    </div> 
            
                                    <div className="mb-4">
                                        <Link href="/checkout">
                                            <h5>
                                                <button className="btn btn-primary mr-1 btn-lg btn-block">Get warm Munchies Delivered&#128666;</button>
                                                <div className="alert alert-warning emailPadding" role="alert">
                                                    We're running out of stock!
                                                </div>
                                            </h5>
                                        </Link>
                                    </div>
                                    
                                </article> 
                            </main>
                            <aside className="col-md-6">
                                <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-indicators">
                                <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class=""></button>
                                <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class="active" aria-current="true"></button>
                                </div>
                                <div class="carousel-inner">
                                    <div class="carousel-item">
                                        {/* <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg> */}
                                        <img class="d-block w-100" src="https://images.unsplash.com/photo-1579546929662-711aa81148cf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt="First slide" />

                                        <div class="container">
                                            <div class="carousel-caption text-start">
                                                <h1>You before Crack Cookies</h1>
                                                <p>Some representative placeholder content for the first slide of the carousel.</p>
                                                {/* <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p> */}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="carousel-item">
                                        {/* <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg> */}
                                        <img class="d-block w-100" src="https://images.unsplash.com/photo-1579546929662-711aa81148cf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt="First slide" />

                                        <img className="bd-placeholder-img"/>
                                        <div class="container">
                                        <div class="carousel-caption">
                                            <h1>You after Crack Cookies.</h1>
                                            <p>Some representative placeholder content for the second slide of the carousel.</p>
                                            {/* <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p> */}
                                        </div>
                                        </div>
                                    </div>
                                    <div class="carousel-item active">
                                        {/* <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg> */}
                                        <img class="d-block w-100" src="https://images.unsplash.com/photo-1579546929662-711aa81148cf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt="First slide" />

                                        <div class="container">
                                        <div class="carousel-caption text-end">
                                            <h1>One more for good measure.</h1>
                                            <p>Some representative placeholder content for the third slide of this carousel.</p>
                                            {/* <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p> */}
                                        </div>
                                        </div>
                                    </div>
                                    </div>
                                        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                            <span class="visually-hidden">Previous</span>
                                        </button>
                                        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                            <span class="visually-hidden">Next</span>
                                        </button>
                                </div>
                                {/* Email Collection */}
                                <div className="emailPadding">
                                    <form onSubmit={ handleSubmit(onSubmit) }>
                                        <label htmlFor="email">Email</label>
                                        <div className="row">
                                            <div className="col-md-8">
                                                <input 
                                                    {...register("email", { required: true, maxLength: 20, // pattern: 
                                                        // {
                                                        //     value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                                                        //     message: "invalid email address"
                                                        // } 
                                                    })} 
                                                    className="form-control col-md-9"
                                                    placeholder="you@example.com"
                                                />
                                            </div>
                                            <div className="col-md-3">
                                                <input className="btn btn-primary" type="submit" value="Your Cookie Updates"/>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </aside>
                        </div> 
                </div> 
            </article>
            <article className="card mt-5">
                <div className="card-body">
                    <div className="row">
                        {/* Reviews */}
                        <aside className="col-md-6">
                            <h5>Berlin Reviews</h5>
                                <dl className="row">
                                    <div>
                                        <div className="row">
                                            <img className="rounded-circle img-fluid col-md-3" src="assets/img/1.jpg" maxWidth/>
                                            <div className="col-md-9">
                                                <p className="description">I was hungry... I was tired... and I then I was satisfied. Nothing like a fresh delivered cookie when your eyes are red and you can&apos;t make it past the door.</p>
                                                <div className="row">
                                                    <h6 className="title">Alex Lemke</h6>
                                                    <small>Berlin, Schöneberg</small>   
                                                </div>
                                                
                                            </div>
                                        </div>
                                        
                                    </div>
                                    <hr/>
                                    <div>
                                        <div className="row">
                                            <img className="rounded-circle img-fluid col-md-3" src="assets/img/1.jpg" maxWidth/>
                                            <div className="col-md-9">
                                                <p className="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                                                <h6 className="title">Ben Johnson</h6>
                                                <small>Berlin, Schöneberg</small>
                                            </div>
                                        </div>
                                        
                                    </div>
                                
                            </dl>
                        </aside>
                        <aside className="col-md-6">
                            <h5>Features</h5>
                            <ul className="list-check">
                                <li >Best performance of battery</li>
                                <li >5 years warranty for this product</li>
                                <li >Amazing features and high quality</li>
                                <li >Best performance of battery</li>
                                <li >Best performance of battery</li>
                                <li >5 years warranty for this product</li>
                            </ul>
                        </aside>
                    </div> 
                    <hr />
                    <div className="row">
                        <Link href="/checkout">
                            <button className="btn btn-primary btn-lg btn-block">
                                <h5>
                                    Get yours&#128666;
                                </h5>
                            </button>
                        </Link>
                        <div className='emailPadding'>
                            <form onSubmit={ handleSubmit(onSubmit) }>
                                <label htmlFor="email">Email</label>
                                <div className="row">
                                    <div className="col-md-8">
                                        <input 
                                            {...register("email", { required: true, maxLength: 20, // pattern: 
                                                // {
                                                //     value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                                                //     message: "invalid email address"
                                                // } 
                                            })} 
                                            className="form-control col-md-9"
                                            placeholder="you@example.com"
                                        />
                                    </div>
                                    <div className="col-md-3">
                                        <input className="btn btn-primary" type="submit" value="Get email Updates"/>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <hr />
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div> 
            </article>
            </div>
            

        </section>
        </main>

        <footer className="section-footer border-top padding-y">
            <div className="container d-flex justify-content-center">
            <p>
                <Link href="/terms-conditions">
                    Terms and conditions
                    </Link>
            </p>
            </div>
            <div className="container d-flex justify-content-center">
                <p className="float-md-right"> 
                &copy; Copyright 2021 All rights reserved
            </p>
            </div>
        
        </footer>


        </div>
    )
}
